### ISSUE TITLE
Ignore disks with no FS type

### ISSUE THREAD

**Issue by gifter77** [ShadowBlip/steam-removable-media#16]
Some disks like Microsoft Reserved Partitions have no FS type or label. I think this should be ignored in mount-media.sh script with something like this in do_mount():
```
	if [[ ${ID_FS_TYPE} == "" ]]; then
	    exit 0
	fi
```

This avoids printing errors on startup for systems that have Windows/ChimeraOS dual boot for example.

**Comment by pastaq** [comment]
That's good to know. Feel free to PR it.

**Comment by gifter77** [comment]
I've raised a PR.
