### ISSUE TITLE
[Feature] Automatically handle symbolic links for ShaderCache/compatdat for the Steam Deck

### ISSUE THREAD

**Issue by ruineka** [ShadowBlip/steam-removable-media#2]
We want to link these local directories to any mounted SD card media on the fly. The reason for this is pretty obvious, the 64GB steam deck runs out of space quickly when games installed on an SD card put these files on the internal emmc eating up all the space. We should be putting these files where the games are stored.

/home/deck/.steam/steam/steamapps/compatdata
/home/deck/.steam/steam/steamapps/shadercache

**Comment by pastaq** [comment]
When testing on the latest steam client on desktop, out appears they have already started doing this.

**Comment by pastaq** [comment]
Is this still an issue?
